- hosts: all
  become: yes
  user: ubuntu
  gather_facts: no
  pre_tasks:
  - name 'update repo'
    shell: 'apt-get update'
  - name: 'install python'
    shell: 'apt-get -y install python'
  roles:
  - install-k8s

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - create-cluster

- hosts: k8s-workers
  become: yes
  user: ubuntu
  roles:
  - join-workers

- hosts: k8s-master
  become: yes
  user: ubuntu
  roles:
  - install-helms